### ISSUE TITLE
在1.4中发消息会出现E/main: Exception in coroutine <unnamed>的红字，但是在1.2中不会

### ISSUE THREAD

**Issue by a792957575** [xtexChooser/mirai-repeater#8]
![image](https://user-images.githubusercontent.com/46198414/132069464-3414420c-cd3e-40e8-8f84-8caaa02c0413.png)
另附上配置方便检查
![image](https://user-images.githubusercontent.com/46198414/132069747-4ca256db-f77c-4083-8071-6aeadf6c97d9.png)
![image](https://user-images.githubusercontent.com/46198414/132069773-810dccb5-b08f-4503-a058-3e066dc4297c.png)

**Comment by xtexChooser** [comment]
az让我看看

**Comment by xtexChooser** [comment]
另外，请直接复制完整日志出来，还有，发下`config/repeater/General.yml`

**Comment by xtexChooser** [comment]
另外，请直接复制完整日志出来，还有，发下`config/repeater/General.yml`

**Comment by a792957575** [comment]
我那个路径下没有General.yml这个文件哎，不过倒是有在date/Repeater发现这个文件，文件打包上传了，这是完整的日志，不过感觉看不出什么问题？我有尝试将date/Repeater路径下的General.yml转移到config/repeater/里，但是似乎没什么效果
![K)}@8R10J73}3T_5(M5WDA](https://user-images.githubusercontent.com/46198414/132084760-89b12a20-1b46-4944-9d3e-87cf098eb888.png)

[General.zip](https://github.com/xtexChooser/mirai-repeater/files/7109290/General.zip)

**Comment by xtexChooser** [comment]
> 我那个路径下没有General.yml这个文件哎，不过倒是有在date/Repeater发现这个文件，文件打包上传了，这是完整的日志，不过感觉看不出什么问题？我有尝试将date/Repeater路径下的General.yml转移到config/repeater/里，但是似乎没什么效果
> ![K)}@8R10J73}3T_5(M5WDA](https://user-images.githubusercontent.com/46198414/132084760-89b12a20-1b46-4944-9d3e-87cf098eb888.png)
> 
> [General.zip](https://github.com/xtexChooser/mirai-repeater/files/7109290/General.zip)

日志后面没了吗?

**Comment by a792957575** [comment]
妹有了妹有了，再输入信息也是出现一样的报错😶

**Comment by xtexChooser** [comment]
> 妹有了妹有了，再输入信息也是出现一样的报错😶

重启下bot还会的话，我推送个fix试试

**Comment by xtexChooser** [comment]
[repeater-1.4.jar.zip](https://github.com/xtexChooser/mirai-repeater/files/7109358/repeater-1.4.jar.zip)


> 妹有了妹有了，再输入信息也是出现一样的报错😶

试试这个行不行

**Comment by a792957575** [comment]
> [repeater-1.4.jar.zip](https://github.com/xtexChooser/mirai-repeater/files/7109358/repeater-1.4.jar.zip)
> 
> > 妹有了妹有了，再输入信息也是出现一样的报错😶
> 
> 试试这个行不行

没变化啊，还是这个样子，有可能是1.4的依赖相比1.2有所变化吗？
![image](https://user-images.githubusercontent.com/46198414/132099767-85ec3e1d-32d2-4708-8af0-52ee99bec000.png)

**Comment by xtexChooser** [comment]
[repeater-1.4.zip](https://github.com/xtexChooser/mirai-repeater/files/7110784/repeater-1.4.zip)
这个呢

**Comment by a792957575** [comment]
> [repeater-1.4.zip](https://github.com/xtexChooser/mirai-repeater/files/7110784/repeater-1.4.zip)
> 这个呢

顺利成功地运行了！

**Comment by a792957575** [comment]
> [repeater-1.4.zip](https://github.com/xtexChooser/mirai-repeater/files/7110784/repeater-1.4.zip)
> 这个呢

噢等等，该版本似乎存在除了全局复读以外所有功能都无法正常使用的问题，以下是测试的结果；
![image](https://user-images.githubusercontent.com/46198414/132129275-67d38644-3430-4145-8564-f280b9c1b237.png)
另外我觉得你可能会用上这个/data/Repeater下的配置文件截图，所以就一起发上来了
![image](https://user-images.githubusercontent.com/46198414/132129374-1c967d51-083b-4bda-8ee4-14ff2054b6bc.png)

**Comment by xtexChooser** [comment]
> > [repeater-1.4.zip](https://github.com/xtexChooser/mirai-repeater/files/7110784/repeater-1.4.zip)
> > 这个呢
> 
> 噢等等，该版本似乎存在除了全局复读以外所有功能都无法正常使用的问题，以下是测试的结果；
> ![image](https://user-images.githubusercontent.com/46198414/132129275-67d38644-3430-4145-8564-f280b9c1b237.png)
> 另外我觉得你可能会用上这个/data/Repeater下的配置文件截图，所以就一起发上来了
> ![image](https://user-images.githubusercontent.com/46198414/132129374-1c967d51-083b-4bda-8ee4-14ff2054b6bc.png)

很抱歉刚回到家，killChainWith没有设置，默认是“打断施法”，killChainState和chainState都是关闭的，你都没打开这两个功能

**Comment by a792957575** [comment]
> > > [repeater-1.4.zip](https://github.com/xtexChooser/mirai-repeater/files/7110784/repeater-1.4.zip)
> > > 这个呢
> > 
> > 
> > 噢等等，该版本似乎存在除了全局复读以外所有功能都无法正常使用的问题，以下是测试的结果；
> > ![image](https://user-images.githubusercontent.com/46198414/132129275-67d38644-3430-4145-8564-f280b9c1b237.png)
> > 另外我觉得你可能会用上这个/data/Repeater下的配置文件截图，所以就一起发上来了
> > ![image](https://user-images.githubusercontent.com/46198414/132129374-1c967d51-083b-4bda-8ee4-14ff2054b6bc.png)
> 
> 很抱歉刚回到家，killChainWith没有设置，默认是“打断施法”，killChainState和chainState都是关闭的，你都没打开这两个功能

好的好的，设置了killChainWith就正常了，当时觉得有问题就关闭了复读功能...感谢跟进~

**Comment by xtexChooser** [comment]
讲个鬼故事：我因为暂时机器人没开，所以我release完全不测试(doge

**Comment by a792957575** [comment]
> 讲个鬼故事：我因为暂时机器人没开，所以我release完全不测试(doge

说明你群里的复读机还不够多 ×

**Comment by xtexChooser** [comment]
> > 讲个鬼故事：我因为暂时机器人没开，所以我release完全不测试(doge
> 
> 说明你群里的复读机还不够多 ×

多了就更不开了 ×
